[window]
dynamic_padding = true
padding.x = 5
padding.y = 5
opacity = 1
# Changed from "none" to "full" to show the topbar and window buttons
decorations = "full"
# Added title to show in the window bar
title = "Alacritty Terminal"

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#222222"
foreground = "#fff4d2"

[colors.cursor]
text = "#bdae93"
cursor = "#665c54"

[colors.normal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#a89984"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fff4d2"

[font]
size = 14
# Adjusted offset to fix spacing issues
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0


[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]
